version: "3.9"
services:
  redis-stack-dev:
    image: redis/redis-stack:6.2.4-v3
    volumes:
      - "./data:/data" # For keeping actual data
      - "./conf/redis.conf:/redis-stack.conf"
    ports:
      - "6379:6379" # Server
      - "8001:8001" # UI
