version: "3.9"
services:
  postgresql:
    image: postgres:14.5
    restart: always
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d" # For .sql script(s) launched just after startup
      # - "./data:/var/lib/postgresql/data" # For keeping actual data
    ports:
      - "5432:5432"
    environment:
      # RestAPI env variables
      POSTGRES_DB: restapi
      POSTGRES_USER: restapi-user
      POSTGRES_PASSWORD : restapi-pwd